todo/urls.py
from django.urls import path
from .views import CreateTaskView, TaskListView

app_name = "todo"

urlpatterns = [
    path('', TaskListView.as_view(), name="task-list"),
    path('create/', CreateTaskView.as_view(), name="task-create"),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls', namespace="todo")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LoginView.as_view(), name='logout'),
]

todo/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    is_organizor = models.BooleanField(default=False)
    is_member = models.BooleanField(default=True)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    due_date = models.DateField(blank=True, null=True)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    complete = models.BooleanField(blank=True, null=True)
    member = models.ForeignKey("Member", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        Member.objects.create(user=instance, organization=instance.userprofile)

post_save.connect(post_user_created_signal, sender=User)

todo/forms.py
from django import forms
from django.forms import fields
from .models import Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

# https://www.youtube.com/watch?v=I2-JYxnSiB0
# https://www.youtube.com/watch?v=UidskJk0KiE

class DateInput(forms.DateInput):
    input_type = 'date' # https://www.w3schools.com/html/html_form_input_types.asp

class CheckboxInput(forms.CheckboxInput):
    input_type = 'checkbox'

class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'title',
            'description',
            'due_date',
            'complete',
        )
        widgets = {
            'due_date': DateInput(),
            'complete': CheckboxInput(),
        }
        
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

todo/views.py
from django.db import models
from django.db.models import query
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin 
from .forms import CreateTaskForm, SignUpForm
from .models import Task
from django.urls import reverse_lazy, reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.
class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'todo/task_create.html'
    form_class = CreateTaskForm
    model = Task
    login_url = '/login/'

    def get_success_url(self):
        return reverse("todo:task-list")

    def form_valid(self, form):
        task = form.save(commit=False)
        task.organization = self.request.user.userprofile
        task.save()

        return super().form_valid(form)

class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'todo/task_list.html'
    model = Task
    context_object_name = "tasks"
    login_url = '/login/'

    def get_queryset(self):
        user = self.request.user
        if user.is_organizor:
            queryset = Task.objects.filter(organization=user.userprofile, member__isnull=False)
        if user.is_member:
            queryset = Task.objects.filter(organization=user.member.organization, member__isnull=False)
            queryset = Task.objects.filter(member__user=user)
        return super().get_queryset()


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'todo/task_update.html'
    model = Task
    form_class = CreateTaskForm

    def get_success_url(self):
        return reverse("todo:task-list")

class TaskDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'todo/task_delete.html'
    model = Task

    def get_success_url(self):
        return reverse("todo:task-list")

class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'registration/signup.html'

    def get_success_url(self):
        return reverse("login")

templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css">
    </head>
    <body>
        
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
        
        <script src="" async defer></script>
    </body>
</html>

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Todo</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      {% if not request.user.is_authenticated %}
        <a class="mr-5 hover:text-gray-900" href="{% url 'login' %}">Login</a>
      {% else %}
        {% if request.user.is_organizor %}
          <a class="mr-5 hover:text-gray-900" href="{% url 'todo:task-list' %}">Task List</a>
          <a class="mr-5 hover:text-gray-900" href="{% url 'todo:task-create' %}">Create Task</a>
        {% endif %}
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
      <a class="mr-5 hover:text-gray-900" href="{% url 'todo:task-create' %}">Logged in as: {{ request.user.username }}</a>
      <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% else %}
      <a class="mr-5 hover:text-gray-900" href="{% url 'login' %}">Login</a>
    {% endif %}
  </div>
</header>

todo/templates/todo/create_task.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="w-1/4 ax-w-lg mx-auto">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="bg-indigo-500 hover:bg-indigo-600 px-3 py-2 rounded-md mt-5 w-full text-white">
            Create
        </button>
    </form>
</div>
{% endblock content %}

todo/templates/todo/task_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="w-1/4 ax-w-lg mx-auto">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="bg-indigo-500 hover:bg-indigo-600 px-3 py-2 rounded-md mt-5 w-full text-white">
            Create
        </button>
    </form>
</div>
{% endblock content %}

todo/templates/todo/task_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
    <div>
        <a class="hover:text-blue-500" href="{% url 'todo:task-list' %}">Go back to task list</a>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <h1 class="mt-5 text-3xl text-gray-800">Are you sure you want to delete "{{ object }}"?</h1>
        <input type="submit" value="Confirm" class="w-full mt-5 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
    </form>
</div>
{% endblock content %}

todo/templates/todo/task_list.html
{% extends 'base.html' %}
{% block content %}
    <table style="width:50%; margin:auto; margin-top:200px">
        <thead>
            <tr>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Due Date</th>
                <th scope="col">Created Date</th>
            </tr>
        </thead>
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ task.due_date }}</td>
                <td>{{ task.created_date }}</td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
{% endblock %}

todo/templates/todo/task_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% block content %}
<div class="w-1/4 ax-w-lg mx-auto">
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="divide-blue-400">
            <button type="submit" class="bg-indigo-500 hover:bg-indigo-600 px-3 py-2 rounded-md mt-5 w-full text-white">
                Update
            </button>
        </div>
        <div class="mt-6 border-t border-gray-200 py-5">
            <a class="w-auto bg-indigo-500 hover:bg-indigo-600 rounded-md mt-5 text-white px-3 py-2" href="{% url 'todo:task-delete' task.pk %}">Delete</a>
        </div>
    </form>
</div>
{% endblock content %}